--- # ClinGen Gene Dosage Sensitivity
- name: clingen-dosage
  url: https://search.clinicalgenome.org/kb/gene-dosage/download
  file: gene-dosage-sensitivity.tsv
  header_row: 0
  skip_rows: 0,1,2,3,5
  delimiter: comma
  quoting: 0
  strip_hash: 0
  md5_url:
  md5_file:
  template: >
    ClinGen indicates a Dosage Sensitivity assertion for gene {GENE SYMBOL} as of {DATE}, with haploinsufficiency of
    {HAPLOINSUFFICIENCY}, and triploinsufficiency of {TRIPLOSENSITIVITY}.