--- # ClinGen Gene Dosage Sensitivity
- name: clingen-dosage
  suffix: cgdose
  url: https://search.clinicalgenome.org/kb/gene-dosage/download
  file: gene-dosage-sensitivity.tsv
  header_row: 0
  skip_rows: 0,1,2,3,5
  delimiter: comma
  quoting: 0
  strip_hash: 0
  md5_url:
  md5_file:
  template: >
    ClinGen's assessment of the dosage sensitivity of the ${dict['GENE SYMBOL']} gene indicates a haploinsufficiency assertion of 
    {% choose %}
    {% when len(str(dict.HAPLOINSUFFICIENCY)) == 0 %}"not provided"{% end %}
    {% otherwise %}"${dict.HAPLOINSUFFICIENCY}"{% end %}
    {% end %} and a triplosensitivity assertion of {% choose %}
    {% when len(str(dict.TRIPLOSENSITIVITY)) == 0 %}"not provided"{% end %}
    {% otherwise %}"${dict.TRIPLOSENSITIVITY}"{% end %}
    {% end %}. These assertions were made on ${dict.DATE}.