--- # ClinGen Overall Scores Adult
- name: clingen-overall-scores-adult
  url: https://actionability.clinicalgenome.org/ac/Adult/api/summ?format=tsv
  file: clingen-overall-scores-adult.tsv
  header_row: 0
  skip_rows: None
  delimiter: tab
  quoting: 0
  strip_hash: 1
  md5_url:
  md5_file: