--- # ClinGen Overall Scores Adult
- name: clingen-overall-scores-adult
  url: https://actionability.clinicalgenome.org/ac/Adult/api/summ?format=tsv
  file: clingen-overall-scores-adult.tsv
  header_row: 0
  skip_rows: None
  delimiter: tab
  quoting: 0
  strip_hash: 1
  md5_url:
  md5_file:
  template: >
    Clingen's overall adult gene-disease associations indicate pathogenic mutations in gene(s) {geneOrVariant} may be
    associated with condition {disease} with overall status {status-overall} and score {status-scoring}. Potential
    disease outcomes include {outcome}, with potential interventions {intervention}.