--- # GenCC Submissions
- name: gencc-submissions
  url: https://search.thegencc.org/download/action/submissions-export-tsv
  file: gencc-submissions.tsv
  header_row: 0
  skip_rows: 0
  delimiter: tab
  quoting: 0
  strip_hash: 0
  md5_url:
  md5_file: