--- # ClinGen Gene Disease
- name: clingen-gene-disease
  suffix: cggenedis
  url: https://search.clinicalgenome.org/kb/gene-validity/download
  file: gene-disease-summary.tsv
  header_row: 0
  skip_rows: 0,1,2,3,5
  delimiter: comma
  quoting: 0
  strip_hash: 0
  md5_url:
  md5_file:
  template: >
    ClinGen's assessment of the ${dict['GENE SYMBOL']} gene has found an association with ${dict['DISEASE LABEL']} 
    with ${dict.MOI} inheritance pattern. The current classification of this association is ${dict.CLASSIFICATION} 
    as of ${dict['CLASSIFICATION DATE']}. This disease association was reviewed by the ${dict.GCEP} expert panel.