--- # ClinGen Gene Disease
- name: clingen-gene-disease
  url: https://search.clinicalgenome.org/kb/gene-validity/download
  file: gene-disease-summary.tsv
  header_row: 0
  skip_rows: 0,1,2,3,5
  delimiter: comma
  quoting: 0
  strip_hash: 0
  md5_url:
  md5_file: