--- # ClinVar Submission Summary
- name: clinvar-submission-summary
  url: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/submission_summary.txt.gz
  download_file: submission_summary.txt.gz
  gzip: 1
  file: submission_summary.txt
  header_row: 0
  skip_rows: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
  delimiter: tab
  quoting: 3
  strip_hash: 1
  md5_url: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/submission_summary.txt.gz.md5
  md5_file: submission_summary.txt.gz.md5
  template: >
    {Submitter} submitted their laboratory's assertion ClinVar VariationID of {VariationID} on gene 
    {SubmittedGeneSymbol}. {Submitter} indicates an association with {SubmittedPhenotypeInfo} conditions with 
    significance {ClinicalSignificance}. The laboratory most recently evaluated this variant on {DateLastEvaluated}
    with a review status of {ReviewStatus}. That laboratory's basis for this interpretation: {Description}.