--- # ClinGen Consensus Assertions Pediatric
- name: clingen-consensus-assertions-pediatric
  url: https://actionability.clinicalgenome.org/ac/Pediatric/api/summ/assertion?format=tsv
  file: clingen-consensus-assertions-pediatric.tsv
  header_row: 0
  skip_rows: 0
  delimiter: tab
  quoting: 0
  strip_hash: 1
  md5_url:
  md5_file: