--- # ClinGen Consensus Assertions Pediatric
- name: clingen-consensus-assertions-pediatric
  url: https://actionability.clinicalgenome.org/ac/Pediatric/api/summ/assertion?format=tsv
  file: clingen-consensus-assertions-pediatric.tsv
  header_row: 0
  skip_rows: None
  delimiter: tab
  quoting: 0
  strip_hash: 1
  md5_url:
  md5_file:
  template: >
    {% with assertionList = ('Assertion Pending', 'N/A - Insufficient evidence: early rule-out', 'N/A - Insufficient evidence: expert review', 'No Assertion: scoring group absence') %}
    {% choose %}
    {% when dict.consensusAssertion in assertionList %}Currently, ClinGen does not have a consensus assertion for the 
    actionability of the ${dict.geneOrVariant} in the context of “${dict.disease}”. The reason for this is 
    "${dict.consensusAssertion}". This assertion was last updated on ${dict.lastUpdated}.{% end %}
    {% otherwise %}ClinGen's consensus review asserts that there is ${dict.consensusAssertion} clinically for 
    pathogenic variants the ${dict.geneOrVariant} gene in the context ${dict.disease}. The status of this assertion is 
    ${dict['status-assertion']} and the assertion has been ${dict['status-overall']}. This actionability assertion 
    was last updated on ${dict.lastUpdated}.{% end %}{% end %}{% end %}